import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import ClientLayout from "./ClientLayout";

import "./globals.css";

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
})

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >
        <div className="container mx-auto">
        <ClientLayout>{children}</ClientLayout>
        </div>
      </body>
    </html>
  );
}
